
* 

* Reply to referee
:PROPERTIES:
:EXPORT_FILE_NAME: reply-to-referee
:EXPORT_OPTIONS: toc:nil num:nil 
:EXPORT_TITLE: Reply to referee
:EXPORT_AUTHOR: García-Vázquez et al
:END:

: will be happy to recommend the manuscript for publication after some
: clarification of some details:
: 
: To study the Finite box effects, as well as that of seeing the authors
: do an interesting exercise with idealized data (as fractional Brownian
: motion -fBm- 2D data modified to include a correlation taper).  This
: approach is very clear, but there is one issue that requires
: attention, and that is that of the projection from a 3D field to a 2D
: field.  In reality the density/velocity fields are three-dimensional
: but some information is lost in the projection to a 2D map.  For the
: exercise presented in appendix A, the authors use a 2D map that was
: modified to include the proper spectral index (n_2D = m +2) and a
: correlation length r_0, in reality one would have a 3D map with a
: spectral index (n_3D = m +3), which if integrated along the line of
: sight would change the spectral index from n_3D to n_2D (and within
: the transition some inertial range could be 'lost') .
: 
: In other words in the current version of the paper the r_0 is entirely
: in the plane of the sky, while in reality should correspond to the 3D
: field, and at the same time the transition from a 3D to a 2D map could
: curve more the structure functions.  I believe that it would be
: beneficial to obtain the 2D map from collapsing a 3D fBm (with an
: index m+3) and the same exponential taper used and verify that the
: main results hold, or discuss this an additional limitation.

We thank the referee for the insightful comments. It is quite true that our approach of directly simulating 2d maps is not strictly correct and that we should really simulate three dimensional fields and then project them down to two dimensions for further analysis. So, we have done this and the results of Appendix A have now been completely replaced. It turns out that the new results are similar to the old ones, so the changes to the text (highlighted in red in the manuscript) are not large.

One new issue that we had to grapple with in order to use this more realistic approach is that we needed to simulate the three dimensional emissivity field (assumed proportional to ionized density squared for H alpha) as well as the three dimensional velocity field.  For this, we used the results shown in our Figure 12 to estimate the variance in the emissivity, which we assumed to follow a log-normal distribution.  For the spatial properties of the emissivity fluctuations, we assumed that the correlation length and power law index was the same as for the velocity and that the velocity and emissivity fluctuations have no mutual correlation.  We investigated three different values of the rms emissivity dispersion: sigma_E = 0, 1, and 2 (in units of the mean value). The results were very similar in all cases, and we only show the sigma_E = 1 case in the paper, since this is the most appropriate for the majority of our regions.  

With the new results, we found an improved analytic approximation for the effects of seeing (equation 15 and A1). We have therefore re-run all of the model fits in section 4, but the only significant changes were in some of the derived seeing widths. None of the "interesting" parameters (sigma, r0, m) changed by more than 1%. 

We have also taken the opportunity to revise and improve the descriptions of individual regions in Appendix C. All substantial changes are marked in red.

Finally, we have separated the online-only supplementary figures into a separate PDF file, as requested by the editor. 




* Instrumental line width for Giraffe/HR15N
v1 = −6.404371 km s−1 , σ1 = 6.44256 km s−1 , A1 = 0.3966431, v2 = 3.454723 km s−1 , σ2 = 6.069641 km s−1 , and A2 = 0.6033569.

|        I_A |        I_B | v_A        |       v_B |      s_A |       s_B | sigma  |
|-----------+-----------+-----------+----------+---------+----------+--------|
| 0.3966431 | 0.6033569 | −6.404371 | 3.454723 | 6.44256 | 6.069641 | l7.871 |
#+TBLFM: $7=sqrt(  (($1 $5**2 + $2 $6**2) / ($1 + $2)) + (($1 $2) ($3 - $4)**2 / ($1 + $2)**2) ) ; f3


* Correlation length versus box size
| L/r0 |            r0/L |
|------+-----------------|
|    8 |            0.13 |
|   14 |            0.07 |
|   17 |            0.06 |
|    9 |            0.11 |
|   36 |            0.03 |
|   19 |            0.05 |
|    7 |            0.14 |
|   17 |            0.06 |
|   16 |            0.06 |
|------+-----------------|
|      | 0.079 +/- 0.013 |
#+TBLFM: $2=1/$1;f2::@11$2=vmeane(@I..@II);f3

