#+OPTIONS: ^:{}
* Submission to arxiv [2023-06-02 Fri]
:PROPERTIES:
:EXPORT_FILE_NAME: submit-to-arxiv
:EXPORT_OPTIONS: toc:nil num:nil
:END:
- Should be released [2023-06-05 Mon]
- [[file:strucfunc_paper_plus-arxiv.pdf]]
** Problems encountered
- arxiv compiles with a more recent version of the TeX distro (2023) and this causes some errors with siunitx
  - The problem was things like e49.29, which I changed to 1.95e49
  - There were lots of these!
  - But it fixed the problem
** DONE Metadata for arxiv
CLOSED: [2023-06-02 Fri 11:36]
- Title
  - Turbulence in compact to giant H II regions
- Abstract (plain text)
  - 
     : Radial velocity fluctuations on the plane of the sky are a powerful
     : tool for studying the turbulent dynamics of emission line regions. We
     : conduct a systematic statistical analysis of the H alpha velocity
     : field for a diverse sample of 9 H II regions, spanning two orders of
     : magnitude in size and luminosity, located in the Milky Way and other
     : Local Group galaxies. By fitting a simple model to the second-order
     : spatial structure function of velocity fluctuations, we extract three
     : fundamental parameters: the velocity dispersion, the correlation
     : length, and the power law slope. We determine credibility limits for
     : these parameters in each region, accounting for observational
     : limitations of noise, atmospheric seeing, and the finite map size. The
     : plane-of-sky velocity dispersion is found to be a better diagnostic of
     : turbulent motions than the line width, especially for lower luminosity
     : regions where the turbulence is subsonic. The correlation length of
     : velocity fluctuations is found to be always roughly 2% of the H II
     : region diameter, implying that turbulence is driven on relatively
     : small scales. No evidence is found for any steepening of the structure
     : function in the transition from subsonic to supersonic turbulence,
     : possibly due to the countervailing effect of projection
     : smoothing. Ionized density fluctuations are too large to be explained
     : by the action of the turbulence in any but the highest luminosity
     : sources. A variety of behaviors are seen on scales larger than the
     : correlation length, with only a minority of sources showing evidence
     : for homogeneity on the largest scales.
- Authors
  - J. García-Vázquez (1), William J. Henney (2) and H. O. Castañeda (1)
  - ((1) ESFM-IPN, Mexico, (2) IRyA-UNAM, Morelia, Mexico)


** DONE Add the supplementary material
CLOSED: [2023-06-02 Fri 10:46]
- This is in [[file:strucfunc_paper_plus.tex]]

** DONE Collect the figures and check the sizes
CLOSED: [2023-06-02 Fri 10:45]
#+begin_src sh :dir .
  STEM=strucfunc_paper_plus
  grep 'Graphic file' $STEM.log | cut -d ' ' -f2 |xargs du -sk |sort -nr
#+end_src

#+RESULTS:
| 2376 | Figures/hii-region-mosaic.pdf                                |
| 1064 | Figures/velocity-maps-mosaic.pdf                             |
|  968 | Figures/model-strucfunc-annotated.pdf                        |
|  688 | Figures/fake-3d-finite-box-images-ems-fluct_sigE_1.pdf       |
|  268 | Figures/corner-emcee-CarC.pdf                                |
|  264 | Figures/corner-emcee-M8.pdf                                  |
|  260 | Figures/corner-emcee-N604H.pdf                               |
|  252 | Figures/corner-emcee-N595.pdf                                |
|  236 | Figures/fake-3d-seeing-nonp-ems-fluct-thumbnails_sigE_1.pdf  |
|  236 | Figures/corner-emcee-HV.pdf                                  |
|  228 | Figures/corner-emcee-Dor.pdf                                 |
|  224 | Figures/corner-emcee-N346.pdf                                |
|  224 | Figures/corner-emcee-HX.pdf                                  |
|  212 | Figures/corner-emcee-OrionS.pdf                              |
|  212 | Figures/corner-emcee-OrionS.pdf                              |
|   96 | Figures/bright-to-vel-fluct-annotated.pdf                    |
|   92 | Figures/sf-emcee-N604H.pdf                                   |
|   88 | Figures/sf-emcee-OrionLH.pdf                                 |
|   88 | Figures/sf-emcee-N595.pdf                                    |
|   88 | Figures/sf-emcee-N346.pdf                                    |
|   88 | Figures/sf-emcee-HX.pdf                                      |
|   88 | Figures/sf-emcee-HV.pdf                                      |
|   88 | Figures/sf-emcee-Dor.pdf                                     |
|   84 | Figures/sf-emcee-OrionS.pdf                                  |
|   84 | Figures/sf-emcee-M8.pdf                                      |
|   84 | Figures/sf-emcee-CarC.pdf                                    |
|   76 | Figures/corner-emcee-OrionLH.pdf                             |
|   56 | Figures/bright-hist-multi.pdf                                |
|   32 | Figures/fake-seeing-nonp-3d-ems-fluc_m4-reduction_sigE_1.pdf |
|   28 | Figures/pdfs.pdf                                             |
|   28 | Figures/fake-3d-finite-box-strucfunc-ems-fluct_sigE_1.pdf    |
|   28 | Figures/corr-los-vs-pos.pdf                                  |
|   20 | Figures/fake-finite-box-fits-ems-fluct_sigE_1.pdf            |
|   20 | Figures/fake-3d-finite-box-effect-ems-fluct_sigE_1.pdf       |
|   20 | Figures/corr-svsL.pdf                                        |
|   20 | Figures/corr-rvsS.pdf                                        |

None of those look too big

** DONE Find all .tex source files, including \input
CLOSED: [2023-06-02 Fri 10:45]

- Only reliable way I can think of is to grep through the log file
  - That way, we make sure we catch any nested inputs
#+begin_src sh :dir . :results verbatim
  STEM=strucfunc_paper_plus
  grep '(\./.*\.tex' $STEM.log | cut -d '(' -f2  | cut -d ')' -f1 
#+end_src

#+RESULTS:
: ./strucfunc_paper_plus.tex
: ./table-results.tex
: ./Corr.tex
: ./sf_appendix_D.tex
: ./table-fit-parameters.tex

** DONE Make the tar file
CLOSED: [2023-06-02 Fri 10:40]
#+begin_src sh :dir .
  STEM=strucfunc_paper_plus
  FIGFILES="$(grep 'Graphic file' $STEM.log | cut -d ' ' -f2)"
  TEXFILES="$(grep '(\./.*\.tex' $STEM.log | cut -d '(' -f2  | cut -d ')' -f1)"
  tar --format ustar -cvzf ${STEM}-astro-ph.tgz $TEXFILES $STEM.bbl $FIGFILES
#+end_src

#+RESULTS:
** DONE Test the tar file
CLOSED: [2023-06-02 Fri 10:45]
Copy to temporary folder
#+begin_src sh :results verbatim
  STEM=strucfunc_paper_plus
  TMPD=/tmp/arxiv-test-$STEM
  rm -r $TMPD
  mkdir $TMPD
  cp ${STEM}-astro-ph.tgz $TMPD
  ls -ld $TMPD
  ls -l $TMPD
#+end_src

#+RESULTS:
: drwxr-xr-x  3 will  wheel  96 Jun  2 11:42 /tmp/arxiv-test-strucfunc_paper_plus
: total 16872
: -rw-r--r--@ 1 will  wheel  8637183 Jun  2 11:42 strucfunc_paper_plus-astro-ph.tgz

Unpack and check listing
#+begin_src sh :results verbatim :dir /tmp/arxiv-test-strucfunc_paper_plus
  tar -xvzf strucfunc_paper_plus-astro-ph.tgz
  ls -lR .
#+end_src

#+RESULTS:
#+begin_example
total 17328
-rw-r--r--   1 will  wheel     1465 Apr 20 14:27 Corr.tex
drwxr-xr-x  37 will  wheel     1184 Jun  2 11:42 Figures
-rw-r--r--   1 will  wheel     1132 Apr 17 13:21 sf_appendix_D.tex
-rw-r--r--@  1 will  wheel  8637183 Jun  2 11:42 strucfunc_paper_plus-astro-ph.tgz
-rw-r--r--   1 will  wheel    33102 Jun  2 10:20 strucfunc_paper_plus.bbl
-rw-r--r--   1 will  wheel   179432 Jun  2 11:12 strucfunc_paper_plus.tex
-rw-r--r--   1 will  wheel     1374 Dec 19 18:46 table-fit-parameters.tex
-rw-r--r--   1 will  wheel     2885 Apr 21 09:24 table-results.tex

./Figures:
total 17592
-rw-r--r--  1 will  wheel    53654 Dec 12 10:17 bright-hist-multi.pdf
-rw-r--r--  1 will  wheel    97690 Dec 12 10:22 bright-to-vel-fluct-annotated.pdf
-rw-r--r--  1 will  wheel   272159 Apr 18 08:43 corner-emcee-CarC.pdf
-rw-r--r--  1 will  wheel   232758 Apr 18 08:43 corner-emcee-Dor.pdf
-rw-r--r--  1 will  wheel   241313 Apr 18 08:43 corner-emcee-HV.pdf
-rw-r--r--  1 will  wheel   227579 Apr 18 08:43 corner-emcee-HX.pdf
-rw-r--r--  1 will  wheel   268833 Apr 18 08:43 corner-emcee-M8.pdf
-rw-r--r--  1 will  wheel   228494 Apr 18 08:43 corner-emcee-N346.pdf
-rw-r--r--  1 will  wheel   255703 Apr 20 14:27 corner-emcee-N595.pdf
-rw-r--r--  1 will  wheel   262619 Apr 18 08:43 corner-emcee-N604H.pdf
-rw-r--r--  1 will  wheel    77472 Apr 18 08:43 corner-emcee-OrionLH.pdf
-rw-r--r--  1 will  wheel   213453 Apr 18 08:43 corner-emcee-OrionS.pdf
-rw-r--r--  1 will  wheel    27080 Apr 20 14:27 corr-los-vs-pos.pdf
-rw-r--r--  1 will  wheel    16456 Apr 20 14:27 corr-rvsS.pdf
-rw-r--r--  1 will  wheel    19779 Apr 20 14:27 corr-svsL.pdf
-rw-r--r--  1 will  wheel    19295 Apr 14 10:09 fake-3d-finite-box-effect-ems-fluct_sigE_1.pdf
-rw-r--r--  1 will  wheel   703097 Apr 14 10:09 fake-3d-finite-box-images-ems-fluct_sigE_1.pdf
-rw-r--r--  1 will  wheel    25631 Apr 14 10:09 fake-3d-finite-box-strucfunc-ems-fluct_sigE_1.pdf
-rw-r--r--  1 will  wheel   241411 Apr 14 10:09 fake-3d-seeing-nonp-ems-fluct-thumbnails_sigE_1.pdf
-rw-r--r--  1 will  wheel    19024 Apr 14 10:09 fake-finite-box-fits-ems-fluct_sigE_1.pdf
-rw-r--r--  1 will  wheel    31392 Apr 14 10:09 fake-seeing-nonp-3d-ems-fluc_m4-reduction_sigE_1.pdf
-rw-r--r--  1 will  wheel  2431067 Jun  2 10:17 hii-region-mosaic.pdf
-rw-r--r--  1 will  wheel   988000 Feb 18  2022 model-strucfunc-annotated.pdf
-rw-r--r--  1 will  wheel    27794 Jul  8  2022 pdfs.pdf
-rw-r--r--  1 will  wheel    84065 Apr 18 08:43 sf-emcee-CarC.pdf
-rw-r--r--  1 will  wheel    87944 Apr 18 08:43 sf-emcee-Dor.pdf
-rw-r--r--  1 will  wheel    89155 Apr 18 08:43 sf-emcee-HV.pdf
-rw-r--r--  1 will  wheel    86621 Apr 18 08:43 sf-emcee-HX.pdf
-rw-r--r--  1 will  wheel    85072 Apr 18 08:43 sf-emcee-M8.pdf
-rw-r--r--  1 will  wheel    86632 Apr 18 08:43 sf-emcee-N346.pdf
-rw-r--r--  1 will  wheel    86527 Apr 20 14:27 sf-emcee-N595.pdf
-rw-r--r--  1 will  wheel    92075 Apr 18 08:43 sf-emcee-N604H.pdf
-rw-r--r--  1 will  wheel    86994 Apr 18 08:43 sf-emcee-OrionLH.pdf
-rw-r--r--  1 will  wheel    85162 Apr 18 08:43 sf-emcee-OrionS.pdf
-rw-r--r--  1 will  wheel  1085590 Jun  2 10:17 velocity-maps-mosaic.pdf
#+end_example

Test compilation. Make sure to use ~-bibtex-~ option so that it just uses the bbl file
#+begin_src sh :results verbatim :dir /tmp/arxiv-test-strucfunc_paper_plus
  latexmk -pdf --bibtex-cond --quiet strucfunc_paper_plus
  open ./strucfunc_paper_plus.pdf
#+end_src

#+RESULTS:
: This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2021) (preloaded format=pdflatex)
:  restricted \write18 enabled.
: entering extended mode
: This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2021) (preloaded format=pdflatex)
:  restricted \write18 enabled.
: entering extended mode
: This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2021) (preloaded format=pdflatex)
:  restricted \write18 enabled.
: entering extended mode

That worked great. Now ready to upload.

* Reply to referee
:PROPERTIES:
:EXPORT_FILE_NAME: reply-to-referee
:EXPORT_OPTIONS: toc:nil num:nil 
:EXPORT_TITLE: Reply to referee
:EXPORT_AUTHOR: García-Vázquez et al
:END:

: will be happy to recommend the manuscript for publication after some
: clarification of some details:
: 
: To study the Finite box effects, as well as that of seeing the authors
: do an interesting exercise with idealized data (as fractional Brownian
: motion -fBm- 2D data modified to include a correlation taper).  This
: approach is very clear, but there is one issue that requires
: attention, and that is that of the projection from a 3D field to a 2D
: field.  In reality the density/velocity fields are three-dimensional
: but some information is lost in the projection to a 2D map.  For the
: exercise presented in appendix A, the authors use a 2D map that was
: modified to include the proper spectral index (n_2D = m +2) and a
: correlation length r_0, in reality one would have a 3D map with a
: spectral index (n_3D = m +3), which if integrated along the line of
: sight would change the spectral index from n_3D to n_2D (and within
: the transition some inertial range could be 'lost') .
: 
: In other words in the current version of the paper the r_0 is entirely
: in the plane of the sky, while in reality should correspond to the 3D
: field, and at the same time the transition from a 3D to a 2D map could
: curve more the structure functions.  I believe that it would be
: beneficial to obtain the 2D map from collapsing a 3D fBm (with an
: index m+3) and the same exponential taper used and verify that the
: main results hold, or discuss this an additional limitation.

We thank the referee for the insightful comments. It is quite true that our approach of directly simulating 2d maps is not strictly correct and that we should really simulate three dimensional fields and then project them down to two dimensions for further analysis. So, we have done this and the results of Appendix A have now been completely replaced. It turns out that the new results are similar to the old ones, so the changes to the text (highlighted in red in the manuscript) are not large.

One new issue that we had to grapple with in order to use this more realistic approach is that we needed to simulate the three dimensional emissivity field (assumed proportional to ionized density squared for H alpha) as well as the three dimensional velocity field.  For this, we used the results shown in our Figure 12 to estimate the variance in the emissivity, which we assumed to follow a log-normal distribution.  For the spatial properties of the emissivity fluctuations, we assumed that the correlation length and power law index was the same as for the velocity and that the velocity and emissivity fluctuations have no mutual correlation.  We investigated three different values of the rms emissivity dispersion: sigma_E = 0, 1, and 2 (in units of the mean value). The results were very similar in all cases, and we only show the sigma_E = 1 case in the paper, since this is the most appropriate for the majority of our regions.  

With the new results, we found an improved analytic approximation for the effects of seeing (equation 15 and A1). We have therefore re-run all of the model fits in section 4, but the only significant changes were in some of the derived seeing widths. None of the "interesting" parameters (sigma, r0, m) changed by more than 1%. 

We have also taken the opportunity to revise and improve the descriptions of individual regions in Appendix C. All substantial changes are marked in red.

Finally, we have separated the online-only supplementary figures into a separate PDF file, as requested by the editor. 




* Instrumental line width for Giraffe/HR15N
v1 = −6.404371 km s−1 , σ1 = 6.44256 km s−1 , A1 = 0.3966431, v2 = 3.454723 km s−1 , σ2 = 6.069641 km s−1 , and A2 = 0.6033569.

|        I_A |        I_B | v_A        |       v_B |      s_A |       s_B | sigma  |
|-----------+-----------+-----------+----------+---------+----------+--------|
| 0.3966431 | 0.6033569 | −6.404371 | 3.454723 | 6.44256 | 6.069641 | l7.871 |
#+TBLFM: $7=sqrt(  (($1 $5**2 + $2 $6**2) / ($1 + $2)) + (($1 $2) ($3 - $4)**2 / ($1 + $2)**2) ) ; f3


* Correlation length versus box size
| L/r0 |            r0/L |
|------+-----------------|
|    8 |            0.13 |
|   14 |            0.07 |
|   17 |            0.06 |
|    9 |            0.11 |
|   36 |            0.03 |
|   19 |            0.05 |
|    7 |            0.14 |
|   17 |            0.06 |
|   16 |            0.06 |
|------+-----------------|
|      | 0.079 +/- 0.013 |
#+TBLFM: $2=1/$1;f2::@11$2=vmeane(@I..@II);f3

